#!/usr/bin/env python3
"""
audit_detail_evidence_tags.py — 审计详情页/参数中的技术路由证据, 发现缺失 canonical tag 的产品.

用法:
  python3 scripts/audit_detail_evidence_tags.py [--fix] [--dry-run]
  
输出:
  reports/detail_evidence_audit.md  — 审计报告
  reports/manual_review_candidates.md — 需 FAE 确认项
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path
from typing import List

from semantic_registry import DEFAULT_REGISTRY_PATH, filter_rules_with_regex

ROOT = Path(__file__).resolve().parent.parent
DATA_PATH = ROOT / "web" / "public" / "data" / "products_structured.json"
RULES_PATH = DEFAULT_REGISTRY_PATH
REPORTS_DIR = ROOT / "reports"

DRY_RUN = "--dry-run" in sys.argv
DO_FIX = "--fix" in sys.argv


def product_has_include(product: dict, includes: List[str]) -> bool:
    feats = set((product.get("_features") or "").split())
    return any(inc in feats for inc in includes)


def search_evidence(product: dict, fields: List[str], regex: re.Pattern) -> List[tuple]:
    hits = []
    for field in fields:
        text = product.get(field, "") or ""
        if not text:
            continue
        for m in regex.finditer(text):
            start = max(0, m.start() - 30)
            end = min(len(text), m.end() + 30)
            snippet = text[start:end].replace("\n", " ")
            hits.append((field, snippet.strip()))
    return hits


def main() -> int:
    data = json.loads(DATA_PATH.read_text())
    rules = filter_rules_with_regex(RULES_PATH)
    REPORTS_DIR.mkdir(parents=True, exist_ok=True)

    auto_fix_candidates = []
    review_required = []
    unsupported_tags = []
    fixed_count = 0

    for vendor_name, vendor_data in data.items():
        if not isinstance(vendor_data, dict):
            continue
        for product in vendor_data.get("products", []):
            pn = product.get("part_number", "?")
            features = set((product.get("_features") or "").split())

            for rule in rules:
                tag = str(rule["tag"])
                includes = list(rule.get("include", []))
                excludes = list(rule.get("exclude", []))
                fields = list(rule.get("fields", ["_detail_intro", "_detail_features"]))
                auto = bool(rule.get("auto", False))
                regex_str = str(rule.get("regex", ""))
                if not regex_str:
                    continue

                regex = re.compile(regex_str, re.IGNORECASE)

                if includes and not product_has_include(product, includes):
                    continue
                if excludes and product_has_include(product, excludes):
                    continue

                hits = search_evidence(product, fields, regex)

                if hits and tag not in features:
                    entry = (vendor_name, pn, rule, hits)
                    if auto:
                        auto_fix_candidates.append(entry)
                        if DO_FIX and not DRY_RUN:
                            current = product.get("_features", "")
                            product["_features"] = (current + " " + tag).strip()
                            fixed_count += 1
                    else:
                        review_required.append(entry)
                elif not hits and tag in features:
                    unsupported_tags.append((vendor_name, pn, rule))

    audit_md = REPORTS_DIR / "detail_evidence_audit.md"
    with open(audit_md, "w") as f:
        f.write("# Detail Evidence Audit\n\n")
        f.write("Generated by `scripts/audit_detail_evidence_tags.py`\n\n")
        f.write(f"Source registry: `{RULES_PATH}`\n\n")
        f.write(f"## 可自动修复 ({len(auto_fix_candidates)} 项)\n\n")
        if auto_fix_candidates:
            f.write("| PN | vendor | category | missing_tag | evidence_field | evidence_snippet |\n")
            f.write("|---|---|---|---|---|---|\n")
            for vendor_name, pn, rule, hits in auto_fix_candidates:
                tag = rule["tag"]
                category = ",".join(rule.get("include", []))
                field, snippet = hits[0]
                f.write(f"| {pn} | {vendor_name} | {category} | {tag} | {field} | {snippet[:80]} |\n")
        else:
            f.write("无。\n")

        f.write(f"\n## 需人工审核 ({len(review_required)} 项)\n\n")
        if review_required:
            f.write("| PN | vendor | candidate_tag | reason | evidence_snippet |\n")
            f.write("|---|---|---|---|---|\n")
            for vendor_name, pn, rule, hits in review_required:
                tag = rule["tag"]
                reason = rule.get("auto_reason", "auto=false, 需确认")
                _, snippet = hits[0] if hits else ("", "")
                f.write(f"| {pn} | {vendor_name} | {tag} | {reason} | {snippet[:80]} |\n")
        else:
            f.write("无。\n")

        f.write(f"\n## 可疑标签 (有tag无证据) ({len(unsupported_tags)} 项)\n\n")
        if unsupported_tags:
            f.write("| PN | vendor | tag |\n")
            f.write("|---|---|---|\n")
            for vendor_name, pn, rule in unsupported_tags:
                f.write(f"| {pn} | {vendor_name} | {rule['tag']} |\n")
        else:
            f.write("无。\n")

    review_md = REPORTS_DIR / "manual_review_candidates.md"
    with open(review_md, "w") as f:
        f.write("# Manual Review Candidates\n\n")
        f.write(f"## A 类: 确定可自动修复 ({len(auto_fix_candidates)} 项)\n\n")
        f.write("以下项证据明确、无歧义，已由 registry 规则自动识别。\n\n")
        for vendor_name, pn, rule, hits in auto_fix_candidates:
            tag = rule["tag"]
            field, snippet = hits[0]
            f.write(f"- **{pn}** ({vendor_name}): `{tag}` ← {field}「{snippet[:80]}」\n")

        f.write(f"\n## B 类: 需 FAE 确认 ({len(review_required)} 项)\n\n")
        if review_required:
            for vendor_name, pn, rule, hits in review_required:
                tag = rule["tag"]
                field, snippet = hits[0]
                f.write(f"- **{pn}** ({vendor_name}): 候选tag=`{tag}`\n")
                f.write(f"  - 命中字段: {field}\n")
                f.write(f"  - 证据片段: 「{snippet[:120]}」\n")
                f.write("  - 为何不自动修: auto=false\n")
                f.write("  - 建议动作: 确认加入 / 忽略 / 新建tag / 改regex\n\n")
        else:
            f.write("无。\n")

    if DO_FIX and fixed_count > 0 and not DRY_RUN:
        json.dump(data, open(DATA_PATH, "w"), ensure_ascii=False, indent=2)
        print(f"Saved {fixed_count} auto-fixes to {DATA_PATH}")

    print("=" * 60)
    print("  Detail Evidence Audit")
    print("=" * 60)
    print(f"  自动修复候选项: {len(auto_fix_candidates)}")
    print(f"  需人工审核:     {len(review_required)}")
    print(f"  可疑标签:       {len(unsupported_tags)}")
    if DRY_RUN:
        print("  (DRY RUN — no data modified)")
    elif DO_FIX:
        print(f"  已修复:         {fixed_count}")
        print(f"  数据已保存:     {DATA_PATH}")
    print(f"  registry:       {RULES_PATH}")
    print(f"  审计报告:       {audit_md}")
    print(f"  确认清单:       {review_md}")

    if auto_fix_candidates:
        print("\n可自动修复项:")
        for vendor_name, pn, rule, hits in auto_fix_candidates:
            field, snippet = hits[0]
            print(f"  [{vendor_name}] {pn}: +{rule['tag']} ← {field}「{snippet[:60]}」")

    if review_required:
        print("\n需确认项:")
        for vendor_name, pn, rule, hits in review_required:
            field, snippet = hits[0]
            print(f"  [{vendor_name}] {pn}: ?{rule['tag']} ← {field}「{snippet[:60]}」")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
