/**
 * param-defs.ts — Single registry for all numerical parameter definitions.
 *
 * Architecture: Every numerical parameter (Mbps, kVrms, Vin, Vout, Iout, 通道, bit, 口)
 * is defined here ONCE.  Parser rules, family extraction, constraint comparison,
 * and validation patterns all derive from this file.
 *
 * Adding a new parameter: add ONE entry to PARAM_DEFS.
 */

// ── Utility ──
function fmtNum(value: number): string {
  return Number.isInteger(value) ? `${value}` : `${parseFloat(value.toFixed(3))}`;
}

// ── Types ──
export interface ParamRule {
  pattern: RegExp;
  extract: (m: RegExpMatchArray) => string[];
}

export interface ParamFamilyResult {
  family: string;
  value: number;
}

export interface ParamDef {
  /** 参数族名，用于 constraint 维度标注和 mustMeta */
  family: string;
  /** 比较方向：>= 需求值≤产品值即满足，<= 需求值≥产品值即满足，range 需求值在[min,max]内，exact 精确匹配 */
  compare: '>=' | '<=' | 'range' | 'exact';
  /** 是否可向下兼容（如 Mbps / 通道 / 端口） */
  downgradable: boolean;
  /** 从 tag 字符串反解出 family+value（用于 paramFamily） */
  tagPattern: RegExp;
  /** 用户 query → tag 的正则提取规则（可多条，覆盖不同表达方式） */
  parserRules: ParamRule[];
  /** 从产品 _features token 中提取数值的模式（默认 = tagPattern.toLowercase） */
  productTokenPattern?: RegExp;
  /** 注入 LLM prompt 的参数行为说明 */
  llmGuidance?: string;
}

// ═══════════════════════════════════════════════════════════
//  PARAM_DEFS — single source of truth
// ═══════════════════════════════════════════════════════════

export const PARAM_DEFS: ParamDef[] = [
  // ── Mbps (速率) ──
  {
    family: 'Mbps', compare: '>=', downgradable: true,
    tagPattern: /^(\d+\.?\d*)Mbps$/,
    parserRules: [
      { pattern: /(\d+\.?\d*)\s*(G|g)\s*bps/i,
        extract: (m) => [`${fmtNum(parseFloat(m[1]) * 1000)}Mbps`] },
      { pattern: /(\d+\.?\d*)\s*(M|m)\s*bps/i,
        extract: (m) => [`${fmtNum(parseFloat(m[1]))}Mbps`] },
      { pattern: /(\d+\.?\d*)\s*(k|K)\s*bps/i,
        extract: (m) => [`${fmtNum(parseFloat(m[1]) / 1000)}Mbps`] },
      { pattern: /(\d+)\s*(M|兆|m)\s*bps/i,
        extract: (m) => [`${fmtNum(parseInt(m[1]))}Mbps`] },
      { pattern: /(\d+)\s*兆(?!欧|克|瓦|安|伏|赫)/i,
        extract: (m) => [`${fmtNum(parseInt(m[1]))}Mbps`] },
      { pattern: /(\d+)\s*M\b(?!\s*(?:bps|Hz|V|A|Ω|W|F|ohm|[a-z]))/i,
        extract: (m) => [`${fmtNum(parseFloat(m[1]))}Mbps`] },
    ],
    productTokenPattern: /^(\d+\.?\d*)mbps$/,
    llmGuidance: '速率: 输出单一真实值标签如50Mbps。用户说"至少50Mbps"用50Mbps(阈值匹配天然覆盖≥语义)',
  },

  // ── kVrms (隔离耐压) ──
  {
    family: 'kVrms', compare: '>=', downgradable: false,
    tagPattern: /^(\d+\.?\d*)kVrms隔离$/,
    parserRules: [
      { pattern: /(\d+\.?\d*)\s*kVrms|(\d+\.?\d*)\s*kV\s*(隔离|隔离电压)/i,
        extract: (m) => [`${m[1]||m[2]}kVrms隔离`] },
    ],
    productTokenPattern: /^(\d+\.?\d*)kvrms/,
    llmGuidance: 'kVrms等级: 仅输出用户明确提到的等级(如"2.5kVrms"→2.5kVrms隔离)。Parser已处理数值提取, 不要额外添加kVrms标签',
  },

  // ── Vin (输入电压) ──
  {
    family: 'Vin', compare: 'range', downgradable: false,
    tagPattern: /^Vin_([\d.]+)V$/,
    parserRules: [
      { pattern: /(-?\d+\.?\d*)\s*V\b(?!\w)/i,
        extract: (m) => { const v = parseFloat(m[1]); return Math.abs(v) >= 0.5 && Math.abs(v) <= 400 ? [`Vin_${fmtNum(v)}V`] : []; } },
    ],
    productTokenPattern: /^vin_([\d.]+)v$/,
    llmGuidance: 'Vin: parser已处理电压数值提取为Vin_XV格式。vinRangeOf做范围匹配。',
  },

  // ── Vout (输出电压) ──
  //   Vout tags are generated by post-processing (step-match / LDO cascade),
  //   not by a direct PARAM_RULE — but paramFamily still needs to recognize them.
  {
    family: 'Vout', compare: 'exact', downgradable: false,
    tagPattern: /^Vout_(-?[\d.]+)V$/,
    parserRules: [],  // no direct parser rule — step-match handles this
    productTokenPattern: /^vout_(-?[\d.]+)v$/,
  },

  // ── Iout (输出电流) ──
  {
    family: 'Iout', compare: '>=', downgradable: false,
    tagPattern: /^Iout_([\d.]+)A$/,
    parserRules: [
      { pattern: /(\d+\.?\d*)\s*A\b(?!\w)/i,
        extract: (m) => { const a = parseFloat(m[1]); return a >= 0.001 && a <= 200 ? [`Iout_${fmtNum(a)}A`] : []; } },
      { pattern: /(\d+)\s*mA\b/i,
        extract: (m) => { const ma = parseInt(m[1]); const a = ma / 1000; return a >= 0.001 && a <= 200 ? [`Iout_${fmtNum(a)}A`] : []; } },
    ],
    productTokenPattern: /^iout_([\d.]+)a$/,
    llmGuidance: 'Iout: parser已处理电流(A/mA)→Iout_XA。constraint层做≥比较。',
  },

  // ── 通道 (channel count, 向下兼容) ──
  {
    family: '通道', compare: '>=', downgradable: true,
    tagPattern: /^(\d+)通道$/,
    parserRules: [
      { pattern: /(\d+)\s*通道/,
        extract: (m) => { const n = parseInt(m[1]); return [32, 16, 8, 4, 2, 1].filter(t => n >= t).map(t => `${t}通道`); } },
      { pattern: /(\d+)\s*路(?:\s*(?:通道|channel|ch|运放|比较器|ADC|DAC|IO|I2C|SPI|模拟开关|视频|隔离|传感器|驱动|LDO|DCDC|PHY|收发))/i,
        extract: (m) => { const n = parseInt(m[1]); return [32, 16, 8, 4, 2, 1].filter(t => n >= t).map(t => `${t}通道`); } },
    ],
  },

  // ── bit (分辨率) ──
  {
    family: 'bit', compare: '>=', downgradable: false,
    tagPattern: /^(\d+)bit$/,
    parserRules: [
      { pattern: /(\d+)\s*bit\b/i,
        extract: (m) => { const b = parseInt(m[1]); return [24, 20, 18, 16, 14, 12, 10, 8].filter(t => b >= t && t <= 24).map(t => `${t}bit`); } },
    ],
  },

  // ── TXTR (收发通道数, 非数值比较, 精确文本匹配) ──
  //   This is NOT a threshold family — no compare/downgradable needed.
  //   Included here so PARAM_RULES auto-generates from one place.
  {
    family: '__txtr__', compare: 'exact', downgradable: false,
    tagPattern: /^(\d+)T(\d+)R$/,
    parserRules: [
      { pattern: /(\d+)\s*T\s*(\d+)\s*R/i,
        extract: (m) => [`${m[1]}T${m[2]}R`] },
      { pattern: /(\d+)\s*发\s*(\d+)\s*收/,
        extract: (m) => [`${m[1]}T${m[2]}R`] },
    ],
  },

  // ── :1 (多路复用器比率, 非数值比较, 精确文本匹配) ──
  {
    family: '__mux__', compare: 'exact', downgradable: false,
    tagPattern: /^(\d+):(\d+)$/,
    parserRules: [
      { pattern: /(\d+)\s*:\s*1\b/,
        extract: (m) => [`${m[1]}:1`] },
    ],
  },

  // ── 口 (以太网端口, 精确匹配 + 向下兼容) ──
  {
    family: '端口', compare: '>=', downgradable: true,
    tagPattern: /^(\d+)口$/,
    parserRules: [
      { pattern: /(\d+)\s*口/,
        extract: (m) => [`${m[1]}口`] },
    ],
  },
];

// ═══════════════════════════════════════════════════════════
//  Derived helpers (consumers call these instead of duplicating)
// ═══════════════════════════════════════════════════════════

/** Auto-generate PARAM_RULES from PARAM_DEFS */
export function getParserRules(): ParamRule[] {
  return PARAM_DEFS.flatMap(d => d.parserRules);
}

/** Extract {family, value} from a tag — unified paramFamily */
export function paramFamily(tag: string): ParamFamilyResult | null {
  for (const d of PARAM_DEFS) {
    // Skip non-threshold families (__txtr__, __mux__)
    if (d.family.startsWith('__')) continue;
    const m = tag.match(d.tagPattern);
    if (m) {
      // For Vin/Vout which may have negative values
      const val = parseFloat(m[1]);
      if (!Number.isNaN(val)) return { family: d.family, value: val };
    }
  }
  return null;
}

/** Families that support downgrade (>= comparison) */
export function getDowngradableFamilies(): Set<string> {
  return new Set(PARAM_DEFS.filter(d => d.downgradable).map(d => d.family));
}

/** Auto-generate VALID_PATTERNS for route.ts soft-audit */
export function getValidPatterns(): RegExp[] {
  return PARAM_DEFS.map(d => d.tagPattern);
}

/** Look up a ParamDef by family name */
export function getParamDef(family: string): ParamDef | undefined {
  return PARAM_DEFS.find(d => d.family === family);
}

/** Map from family → product token regex (lowercased) */
export function getProductTokenPattern(family: string): RegExp | undefined {
  const d = PARAM_DEFS.find(d => d.family === family);
  return d?.productTokenPattern ?? d?.tagPattern;
}
